version: '3.9'
services:
  # Nacos节点1
  nacos-1:
    image: nacos/nacos-server:1.4.2
    container_name: nacos-1
    hostname: nacos-1
    restart: always
    volumes:
      - ./nacos/nacos-1/logs:/home/nacos/logs
      - ./nacos/nacos-1/conf/cluster.conf:/home/nacos/conf/cluster.conf
    environment:
      PREFER_HOST_MODE: hostname
      MODE: cluster
      NACOS_AUTH_IDENTITY_KEY: sybx
      NACOS_AUTH_IDENTITY_VALUE: hebi
      NACOS_AUTH_TOKEN: sybx@hebi012345678901234567890123456789012345678901234567890123456789
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos-1
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: mysql@2023
      NACOS_SERVERS: nacos-1:8848 nacos-2:8848 nacos-3:8848
    ports:
      - "8848:8848"

  # Nacos节点2
  nacos-2:
    image: nacos/nacos-server:1.4.2
    container_name: nacos-2
    hostname: nacos-2
    restart: always
    volumes:
      - ./nacos/nacos-2/logs:/home/nacos/logs
      - ./nacos/nacos-1/conf/cluster.conf:/home/nacos/conf/cluster.conf
    environment:
      PREFER_HOST_MODE: hostname
      MODE: cluster
      NACOS_AUTH_IDENTITY_KEY: sybx
      NACOS_AUTH_IDENTITY_VALUE: hebi
      NACOS_AUTH_TOKEN: sybx@hebi012345678901234567890123456789012345678901234567890123456789
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos-2
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: mysql@2023
      NACOS_SERVERS: nacos-1:8848 nacos-2:8848 nacos-3:8848
    ports:
      - "8849:8848"

  # Nacos节点3
  nacos-3:
    image: nacos/nacos-server:1.4.2
    container_name: nacos-3
    hostname: nacos-3
    restart: always
    volumes:
      - ./nacos/nacos-3/logs:/home/nacos/logs
      - ./nacos/nacos-1/conf/cluster.conf:/home/nacos/conf/cluster.conf
    environment:
      PREFER_HOST_MODE: hostname
      MODE: cluster
      NACOS_AUTH_IDENTITY_KEY: sybx
      NACOS_AUTH_IDENTITY_VALUE: hebi
      NACOS_AUTH_TOKEN: sybx@hebi012345678901234567890123456789012345678901234567890123456789
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos-3
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: mysql@2023
      NACOS_SERVERS: nacos-1:8848 nacos-2:8848 nacos-3:8848
    ports:
      - "8850:8848"